# Generated by Django 5.2.4 on 2025-08-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('faculty', models.CharField(choices=[('Dasturiy injiniring', 'Dasturiy injiniring'), ('Energetika', 'Energetika'), ('Avtomatika', 'Avtomatika'), ('Iqtisodiyot', 'Iqtisodiyot'), ('Qurilish', 'Qurilish')], max_length=50)),
                ('course', models.CharField(choices=[('1-kurs', '1-kurs'), ('2-kurs', '2-kurs'), ('3-kurs', '3-kurs'), ('4-kurs', '4-kurs'), ('5-kurs', '5-kurs'), ('6-kurs', '7-kurs')], max_length=20)),
                ('is_reserve', models.BooleanField(default=False, verbose_name='Zaxira o‘yinchi')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Jamoa nomi')),
                ('captain_phone', models.CharField(max_length=20, verbose_name='Sardor telefon raqami')),
                ('reserve_phone', models.CharField(max_length=20, verbose_name='Zaxira o‘yinchi telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='apps.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='apps.team'),
        ),
    ]
