# Generated by Django 5.2.4 on 2025-08-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain_phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_team', to='apps.player'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='course',
            field=models.IntegerField(choices=[(1, '1-kurs'), (2, '2-kurs'), (3, '3-kurs'), (4, '4-kurs'), (5, '5-kurs')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='faculty',
            field=models.CharField(choices=[('IT', 'Informatika texnologiyalari'), ('ENG', 'Muhandislik'), ('MED', 'Tibbiyot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='reserve_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
